# https://www.digitalocean.com/community/tutorials/how-to-automate-deployments-to-digitalocean-kubernetes-with-circleci
---
apiVersion: v1
kind: Namespace
metadata:
  name: tete
---
apiVersion: v1
kind: Service
metadata:
  name: tete-db-svc
  namespace: tete
spec:
  selector:
    app: tete-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: tete-web-svc
  namespace: tete
spec:
  selector:
    app: tete-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tete-web
  namespace: tete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tete-web
  template:
    metadata:
      labels:
        app: tete-web
    spec:
      containers:
        - name: tete-web
          image: puremunky/tete-web:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          env:
            - name: ASPNETCORE_URLS
              value: https://+:443;http://+:80
            - name: ASPNETCORE_Kestrel__Certificates__Default__Path
              value: ./Tete.Web.pfx
            - name: ASPNETCORE_Kestrel__Certificates__Default__Password
              valueFrom:
                secretKeyRef:
                  name: cert-credentials
                  key: cert-password
            - name: ConnectionStrings__DefaultConnection # Server=$teteDBServer; Database=Tete; User ID=$teteDBUser; Password=$teteDBPassword
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: connection-string

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tete-db
  namespace: tete
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tete-db
  template:
    metadata:
      labels:
        app: tete-db
    spec:
      containers:
        - name: tete-db
          image: puremunky/tete-db:latest
          ports:
            - containerPort: 1433
          env:
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
